[Rebuild] inner round rect reusable view 재사용가능한 뷰로 디렉터리 변경 및 추가 기능 구현
IF-TG/iOS pull request #132
Opened 2023-10-18 08:20 UTC by SHcommit

🚨 **Your checklist for this pull request** 

- [x]  Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!

- [x]  Check the commit's or even all commits' message styles matches our requested structure.

## 📌 [요약]

- Closed #127 

- InnerRoundRectReusableView를 상속받은 자식타입에서 private인 shadow layer 객체의 shadow를 적용할 수 있게 리빌딩했습니다.

## ✨ [작업 내용]

<img src="https://github.com/IF-TG/iOS/assets/96910404/3e3172e1-e3be-43ec-b37a-a76cc8a9e367" width="250">|
|:-:|
|`InnerRoundRectReusableView기반 화면`|

CollectionView에서 section의 background를 쉽게 커스텀할 수 있는 Decorationview인 UICollectionReusableView는 init(frame:)으로만 생성 및 재사용큐에서 호출되어 재사용됩니다.

Feed화면 말고도 다른 화면에서도 재사용 된다는 것을 알게 되어 리빌딩 했습니다. 

InnerRoundRectReusableView를 데코레이션뷰로 layout에 등록했을 때, 초기에 init(frame:)으로 객체가 생성되고 이 section의 데코레이션 객체를 얻어와 다루지는 못했습니다. 그래서 이를 상속받은 자식 타입에서 쉽게 shadow의 색을 변형하고 적용 후 초기 init 시점에 서로 다른 shadow를 생성할 수 있도록 리빌딩했습니다.

## 📸  [사용 방법]

InnerRoundRectReusableView의 **shadowState**를 변경해주면 됩니다.

```
final class SearchInnerRoundRectReusableView: InnerRoundRectReusableView {
  static let id = String(describing: SearchInnerRoundRectReusableView.self)
  init(frame: CGRect) {
    super.init(shadowType: .search, frame: frame)
  }
  required init?(coder: NSCoder) { nil }
}
```

위 경우처럼 InnerRoundRectReusableView를 상속받은 자식 뷰를 구현할 때, init시점에 shadowType을 feed, search로지정하거나 custom으로 shadow info를 할당해주면 됩니다. 그 후 자식객체를 DecorationView를 등록하고, section 데코레이션 뷰로 추가하면 됩니다.

![image](https://github.com/IF-TG/iOS/assets/96910404/ea4417bd-ae57-45c6-bc4b-0d06a1033e4a)

기본적으로 InnerRoundRectReusableView의 shadowState는 feed입니다. 그러나 원할 경우 위의 경우처럼 search나 custom으로 shadow를 지정할 수 있습니다. 아래는 커스텀 쉐도우 예시입니다.

### 커스텀 예시

![image](https://github.com/IF-TG/iOS/assets/96910404/8e2db3b2-15e8-44b8-ab1a-aa66871f5178)

<img src="https://github.com/IF-TG/iOS/assets/96910404/35e55c05-4e27-4e78-9ad1-0a4d7c78f809" width="250">|
|:-:|
|`데코레이션 등록 및 section 추가 결과`|

2023-10-18 10:32 UTC, letusHyun requested changes

2023-10-18 10:32 UTC, letusHyun commented on travelPlan/Source/Common/View/InnerRoundRectReusableView.swift
> +    }
어차피 해당 뷰를 사용하려면, InnerRoundRectReusableView를 상속하는 하위 뷰 클래스를 정의해주어야 하네요. 그렇다면 굳이 InnerRoundRectReusableView에서 enum으로 case를 정의해주지 않고(부모뷰에서 enum ShadowType 정의와 프로퍼티 제거), 하위뷰에서 shadow를 직접 커스텀하는 방법은 어떨까요? 이렇게 한다면, 부모뷰가 여러 case를 관리하지 않아도 되는 장점이 있을 것 같습니다.

2023-10-18 12:20 UTC, SHcommit commented on travelPlan/Source/Common/View/InnerRoundRectReusableView.swift
> +    }
issue에서 enum처리로하는게 좋을것같다고 해서 이렇게 해봤는데..

다시 생각해보니 shadowInfo 타입을 프로퍼티로 정의하고 자식타입에서 상속받을 경우 명확하게 주입하도록 하면 될 것 같습니다. 
이미 InnerRoundRectReusableView에서 쉐도우를 적용하는 코드가 있기 때문에 이를 최대한 활용하는게 좋을것 같습니다.

2023-10-18 12:43 UTC, SHcommit commented on travelPlan/Source/Common/View/InnerRoundRectReusableView.swift
> +    }
음 그럴까요?

2023-10-18 15:37 UTC, letusHyun approved these changes
확인했습니다 !

2023-10-18 18:26 UTC, letusHyun approved these changes
확인했습니다!

2023-10-18 18:26 UTC, letusHyun commented on travelPlan/Source/Common/View/InnerRoundRectReusableView.swift
>      configureUI()
서브 클래스의 init시점에서 shadowInfo객체를 생성하고, super.init으로 전달해주면 될까요?

2023-10-19 04:43 UTC, SHcommit commented on travelPlan/Source/Common/View/InnerRoundRectReusableView.swift
>      configureUI()
네: )

2023-10-19 07:56 UTC, merged